### ISSUE TITLE
Podman installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by hkcomori** [ikke-t/podman-container-systemd#45]
I ran this role with the following settings to install `podman`.

```yml
skip_podman_install: false
```

However, it failed.
I got the following error.

```
TASK [ikke_t.podman_container_systemd : ensure podman is installed] ***************
fatal: [ubuntu1]: FAILED! => {
    "cache_update_time": 1630881331,
    "cache_updated": false,
    "changed": false,
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: conmon (>= 100:2.0.25~2) but 2.0.9-1 is to be installed
          Depends: crun (>= 100:0.19.1-1) but 0.12.1+dfsg-1 is to be installed
          Recommends: containernetworking-plugins (>= 100:0.9.1-1) but it is not going to be installed



STDERR:

E: Unable to correct problems, you have held broken packages.



MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"       install 'podman'' failed: E: Unable to correct problems, you have held broken packages.
```

It looks like the addition of the kubic repository is not working.
The following [official installation procedure](https://podman.io/getting-started/installation#ubuntu) successfully installed without errors.

```sh
. /etc/os-release
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install podman
```

However, I could not identify the cause.

What am I doing wrong?

Thanks you.

**Comment by ikke-t** [comment]
Let's ask @Yajo , I don't use ubuntu.

**Comment by yajo** [comment]
Sorry I always ran this without podman installation because I have another role that installs it.

Basically, what it does is:

```yaml
# meta/main.yaml
dependencies:
  - role: systemli.apt_repositories
    vars:
      apt_repositories:
        - preset: kubic
    when: |
      (ansible_distribution == 'Debian' and
      ansible_distribution_version is version ('11', '<')) or
      (ansible_distribution == 'Ubuntu' and
      ansible_distribution_version is version('21.04', '<'))
```

```yaml
# tasks/main.yaml
- name: install required packages
  package:
    name:
      - podman
```

And it works.
